version: '3'

services:
    db:
        image: postgres:12
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    blog-service:
        build: ./blog-service
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - ./.env
        volumes:
            - ./blog-service:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
    mongodb:
        image: mongo:latest
        logging:
            driver: none
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
    user-service:
        build: ./user-service
        command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
        env_file:
            - ./.env
        volumes:
            - ./user-service:/code
        ports:
            - "8001:8001"
        depends_on:
            - mongodb
            - redis
    redis:
        image: redis:alpine
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - redis:/data

volumes:
    postgres_data:
    mongo_data:
    redis:
