# Generated by Django 3.1.1 on 2020-10-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
