# Generated by Django 3.1.1 on 2020-11-08 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20201102_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
