# Generated by Django 3.1.1 on 2021-01-04 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='core.article'),
        ),
    ]
