# Generated by Django 3.1.1 on 2020-11-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201031_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecontent',
            name='order_index',
        ),
        migrations.RemoveField(
            model_name='articlecontent',
            name='url',
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
