# Generated by Django 3.1.1 on 2022-11-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloguser",
            name="id",
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
