# Generated by Django 3.1.1 on 2020-11-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201102_1916'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='saved_articles',
            field=models.ManyToManyField(blank=True, related_name='users_saved', to='core.Article'),
        ),
    ]
