# Generated by Django 3.1.1 on 2020-11-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bloguser_saved_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
