# Generated by Django 5.0.1 on 2024-01-11 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_auto_20221129_1827"),
        ("users", "0002_auto_20221129_1858"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="users.bloguser",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="users.bloguser",
            ),
        ),
    ]
